on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        run: |
          git config --global user.email "quarto-github-actions-publish@example.com"
          git config --global user.name "Quarto GHA Workflow Runner"
          quarto publish gh-pages "Blog for Master's thesis" --no-browser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
